output "balancer_ip" {
    value = yandex_alb_load_balancer.alb-1.listener[0].endpoint[0].address[0].external_ipv4_address[0].address
}

output "balancer_inner_ip" {
    value = yandex_alb_load_balancer.alb-1.listener[0].endpoint[0].address[0].internal_ipv4_address[0].address
}

output "instance_1_external_ip" {
  value = yandex_compute_instance_group.alb-vm-group.instances.*.network_interface.0.nat_ip_address[0]
}

output "instance_2_external_ip" {
  value = yandex_compute_instance_group.alb-vm-group.instances.*.network_interface.0.nat_ip_address[1]
}

resource "local_file" "tf_ansible_vars" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    app_port: 80
    redmine_version: latest
    
    db_host: ${yandex_mdb_postgresql_cluster.db-cluster.host.0.fqdn}
    db_username: ${var.db_user}
    db_password: ${var.db_password}
    db_name: ${var.db_name}

    dd_api_key: ${var.dd_api_key}

    vm1_ip: ${yandex_compute_instance_group.alb-vm-group.instances.*.network_interface.0.nat_ip_address[0]}
    vm2_ip: ${yandex_compute_instance_group.alb-vm-group.instances.*.network_interface.0.nat_ip_address[1]}
    vm1_user: ubuntu
    vm2_user: ubuntu
    DOC
  filename = "../ansible/group_vars/all/tf_ansible_vars.yml"
}
